[WIP] Store page
GeoGuesSUUU/GeoGuesSUUU pull request #166
Opened 2023-01-28 22:20 UTC by Zekix27

2023-01-28 23:05 UTC, DRACOX2500 commented on src/Entity/ItemType.php
> +    #[ORM\OneToOne(mappedBy: 'itemType', targetEntity: StoreItem::class, cascade: ['persist'])]
PK t'as enlevé "orphanRemoval: true" et #Groups ?
et aussi pas besoin de mettre targetEntity, c'est déjà typé en dessous

2023-01-28 23:08 UTC, DRACOX2500 commented on src/Entity/StoreItem.php
> +    private ?ItemType $itemType = null;
Pk t'as enlevé #Groups ici aussi ???????????????????
et aussi toujours pas besoin de targetEntity 

<img src="https://media1.giphy.com/media/WLbtNNR5TKJBS/giphy.gif"/>

2023-01-28 23:10 UTC, DRACOX2500 requested changes
C'est de la merde 💩💩💩

2023-01-29 09:32 UTC, Zekix27 commented on src/Entity/ItemType.php
> +    #[ORM\OneToOne(mappedBy: 'itemType', targetEntity: StoreItem::class, cascade: ['persist'])]
Aucune idée, il voulait pas marcher j'ai tester plein de truc et j'ai pas fais gaffe

2023-01-29 16:40 UTC, DRACOX2500 approved these changes

2023-01-29 16:57 UTC, merged